// <auto-generated />
using System;
using EHS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EHS.Migrations
{
    [DbContext(typeof(EHSContext))]
    [Migration("20250528182326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EHS.Models.seg_risk_assessments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("acute_chronic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("assessment_methods_used")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("controls_recommended")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime>("date_conducted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("duration_of_task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exposure_levels_acceptable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exposure_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequency_of_task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("has_agent_been_changed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("monitoring_data_required")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("oel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("person_performing_assessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("route_of_entry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("seg_number_of_workers")
                        .HasColumnType("integer");

                    b.Property<string>("seg_role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("seg_risk_assessments");
                });
#pragma warning restore 612, 618
        }
    }
}
