// <auto-generated />
using System;
using EHS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EHS.Migrations
{
    [DbContext(typeof(EHSContext))]
    [Migration("20250619132549_addRouteOfEntry")]
    partial class addRouteOfEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ehs")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:HistoryTableSchema", "ehs")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EHS.Models.Dropdowns.acute_chronic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("acute_chronic", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.agent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<string>("exposure_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("agent", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.exposure_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("exposure_type", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("location", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.occupational_exposure_limit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("occupational_exposure_limit", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.route_of_entry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("route_of_entry", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.seg_role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("seg_role", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("task", "ehs");
                });

            modelBuilder.Entity("EHS.Models.seg_risk_assessment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("acute_chronic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("assessment_methods_used")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("controls_recommended")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date_conducted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("duration_of_task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exposure_levels_acceptable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exposure_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequency_of_task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("has_agent_been_changed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("monitoring_data_required")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("oel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("person_performing_assessment_displayname")
                        .HasColumnType("text");

                    b.Property<string>("person_performing_assessment_username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("route_of_entry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("seg_number_of_workers")
                        .HasColumnType("integer");

                    b.Property<string>("seg_role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("seg_risk_assessment", "ehs");
                });
#pragma warning restore 612, 618
        }
    }
}
