// <auto-generated />
using System;
using System.Collections.Generic;
using EHS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EHS.Migrations
{
    [DbContext(typeof(EHSContext))]
    [Migration("20250711124446_addInitial")]
    partial class addInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ehs")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:HistoryTableSchema", "ehs")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EHS.Models.Dropdowns.acute_chronic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("acute_chronic", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.agent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<string>("exposure_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("agent", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.assessment_methods_used", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("assessment_methods_used", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.controls_recommended", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("controls_recommended", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.exposure_rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("exposure_rating", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.exposure_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("exposure_type", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.frequency_of_task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("frequency_of_task", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.has_agent_been_changed", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("has_agent_been_changed", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.health_effect_rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("health_effect_rating", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("location", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.monitoring_data_required", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("monitoring_data_required", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.number_of_workers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("number_of_workers", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.occupational_exposure_limit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("occupational_exposure_limit", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.route_of_entry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("route_of_entry", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.seg_role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("seg_role", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("task", "ehs");
                });

            modelBuilder.Entity("EHS.Models.Dropdowns.yes_no", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("display")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("sort_order")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("yes_no", "ehs");
                });

            modelBuilder.Entity("EHS.Models.seg_risk_assessment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("acute_chronic")
                        .HasColumnType("text");

                    b.Property<string>("additional_notes")
                        .HasColumnType("text");

                    b.Property<string>("agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("assessment_methods_used")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("controls_recommended")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("created_user_email")
                        .HasColumnType("text");

                    b.Property<string>("created_user_fullname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date_conducted")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("deleted_user")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_email")
                        .HasColumnType("text");

                    b.Property<string>("deleted_user_fullname")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("duration_of_task")
                        .HasColumnType("interval");

                    b.Property<string>("exposure_levels_acceptable")
                        .HasColumnType("text");

                    b.Property<int?>("exposure_rating")
                        .HasColumnType("integer");

                    b.Property<string>("exposure_rating_description")
                        .HasColumnType("text");

                    b.Property<string>("exposure_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequency_of_task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("has_agent_been_changed")
                        .HasColumnType("text");

                    b.Property<int?>("health_effect_rating")
                        .HasColumnType("integer");

                    b.Property<string>("health_effect_rating_description")
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("modified_user")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_email")
                        .HasColumnType("text");

                    b.Property<string>("modified_user_fullname")
                        .HasColumnType("text");

                    b.Property<string>("monitoring_data_required")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("oel")
                        .HasColumnType("text");

                    b.Property<string>("person_performing_assessment_displayname")
                        .HasColumnType("text");

                    b.Property<string>("person_performing_assessment_username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("risk_score")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("\"exposure_rating\" * \"health_effect_rating\"", true);

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("route_of_entry")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("seg_number_of_workers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("seg_risk_assessment", "ehs");
                });
#pragma warning restore 612, 618
        }
    }
}
