// <auto-generated />
using System;
using System.Collections.Generic;
using Management_of_Change.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Management_of_Change.Migrations.PtnWaiver
{
    [DbContext(typeof(PtnWaiverContext))]
    [Migration("20250106202152_addPtnWaiverContext")]
    partial class addPtnWaiverContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Management_of_Change.Models.PtnWaiver.PTN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedByUser")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedByUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("BouleSize")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletedBylUser")
                        .HasColumnType("text");

                    b.Property<string>("CompletedBylUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DocId")
                        .HasColumnType("text");

                    b.Property<string>("GroupApprover")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("OriginatingGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginatorInitials")
                        .HasColumnType("text");

                    b.Property<string>("OriginatorYear")
                        .HasColumnType("text");

                    b.Property<string>("PdfLocation")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverUsername")
                        .HasColumnType("text");

                    b.Property<string>("PtrNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("RejectedBeforeSubmission")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RejectedByApprover")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverUsername")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("SubmittedForApprovalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubmittedForApprovalUser")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedForApprovalUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PTN", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Management_of_Change.Models.PtnWaiver.Waiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedByUser")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedByUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletedBylUser")
                        .HasColumnType("text");

                    b.Property<string>("CompletedBylUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CorrectiveActionDueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsMostCurrentWaiver")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<int>("PTNId")
                        .HasColumnType("integer");

                    b.Property<string>("PorProject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverUsername")
                        .HasColumnType("text");

                    b.Property<string>("ProductProcess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PtnDocId")
                        .HasColumnType("text");

                    b.Property<bool?>("RejectedBeforeSubmission")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RejectedByApprover")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverUsername")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedForApprovalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubmittedForApprovalUser")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedForApprovalUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("WaiverNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PTNId");

                    b.ToTable("Waiver", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Management_of_Change.Models.PtnWaiver.Waiver", b =>
                {
                    b.HasOne("Management_of_Change.Models.PtnWaiver.PTN", "PTN")
                        .WithMany("Waivers")
                        .HasForeignKey("PTNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PTN");
                });

            modelBuilder.Entity("Management_of_Change.Models.PtnWaiver.PTN", b =>
                {
                    b.Navigation("Waivers");
                });
#pragma warning restore 612, 618
        }
    }
}
