// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PtnWaiver.Data;

#nullable disable

namespace PtnWaiver.Migrations
{
    [DbContext(typeof(PtnWaiverContext))]
    [Migration("20240205142903_initialMigrationPtn")]
    partial class initialMigrationPtn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PtnWaiver.Models.Administrators", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approver")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("PtnWaiver.Models.PTN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PTN");
                });

            modelBuilder.Entity("PtnWaiver.Models.Waiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PTNId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PTNId");

                    b.ToTable("Waiver");
                });

            modelBuilder.Entity("PtnWaiver.Models.Waiver", b =>
                {
                    b.HasOne("PtnWaiver.Models.PTN", null)
                        .WithMany("Waivers")
                        .HasForeignKey("PTNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PtnWaiver.Models.PTN", b =>
                {
                    b.Navigation("Waivers");
                });
#pragma warning restore 612, 618
        }
    }
}
