// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PtnWaiver.Data;

#nullable disable

namespace PtnWaiver.Migrations
{
    [DbContext(typeof(PtnWaiverContext))]
    [Migration("20250818180545_addWaiverQuestions")]
    partial class addWaiverQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PtnWaiver.Models.Administrators", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approver")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("PtnWaiver.Models.AllowedAttachmentExtensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtensionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AllowedAttachmentExtensions");
                });

            modelBuilder.Entity("PtnWaiver.Models.EmailHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<int?>("PtnId")
                        .HasColumnType("integer");

                    b.Property<string>("SentToDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SentToEmail")
                        .HasColumnType("text");

                    b.Property<string>("SentToUsername")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int?>("WaiverId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmailHistory");
                });

            modelBuilder.Entity("PtnWaiver.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("PtnWaiver.Models.GroupApprovers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PtnMandatoryApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverUsername")
                        .HasColumnType("text");

                    b.Property<bool>("WaiverMandatoryApproval")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GroupApprovers");
                });

            modelBuilder.Entity("PtnWaiver.Models.GroupApproversReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminUsername")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryApproverUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverEmail")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverFullName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverTitle")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryApproverUsername")
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupApproversReview");
                });

            modelBuilder.Entity("PtnWaiver.Models.OriginatingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<bool>("ProductSizeRequired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OriginatingGroup");
                });

            modelBuilder.Entity("PtnWaiver.Models.PTN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedByUser")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedByUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletedBylUser")
                        .HasColumnType("text");

                    b.Property<string>("CompletedBylUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("DocId")
                        .HasColumnType("text");

                    b.Property<List<string>>("GroupApprover")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("OriginatingGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginatorInitials")
                        .HasColumnType("text");

                    b.Property<string>("OriginatorYear")
                        .HasColumnType("text");

                    b.Property<string>("PdfLocation")
                        .HasColumnType("text");

                    b.Property<string>("ProductSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PtrNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("RejectedBeforeSubmission")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RejectedByApprover")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("SubmittedForApprovalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubmittedForApprovalUser")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedForApprovalUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isWaferingDepartment")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PTN");
                });

            modelBuilder.Entity("PtnWaiver.Models.PorProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PorProject");
                });

            modelBuilder.Entity("PtnWaiver.Models.ProductProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductProcess");
                });

            modelBuilder.Entity("PtnWaiver.Models.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductSize");
                });

            modelBuilder.Entity("PtnWaiver.Models.PtnStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PtnStatus");
                });

            modelBuilder.Entity("PtnWaiver.Models.SubjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubjectType");
                });

            modelBuilder.Entity("PtnWaiver.Models.Waiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AdditionalEmailNotificationsOfMaterialDetails")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ApprovedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedByUser")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedByUserFullName")
                        .HasColumnType("text");

                    b.Property<List<string>>("Areas")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("CompletedByDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletedBylUser")
                        .HasColumnType("text");

                    b.Property<string>("CompletedBylUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CorrectiveActionDueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DateSequence")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalIdMes")
                        .HasColumnType("text");

                    b.Property<List<string>>("GroupApprover")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool?>("IsMostCurrentWaiver")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialDetailNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<int>("PTNId")
                        .HasColumnType("integer");

                    b.Property<string>("PorProject")
                        .HasColumnType("text");

                    b.Property<List<string>>("ProductProcess")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PtnDocId")
                        .HasColumnType("text");

                    b.Property<bool?>("RejectedBeforeSubmission")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RejectedByApprover")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedForApprovalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubmittedForApprovalUser")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedForApprovalUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("WaiverNumber")
                        .HasColumnType("text");

                    b.Property<string>("WaiverSequence")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PTNId");

                    b.ToTable("Waiver");
                });

            modelBuilder.Entity("PtnWaiver.Models.WaiverQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<List<string>>("GroupApprover")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WaiverQuestion");
                });

            modelBuilder.Entity("PtnWaiver.Models.WaiverQuestionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<List<string>>("GroupApprover")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<int>("WaiverId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WaiverQuestionResponse");
                });

            modelBuilder.Entity("PtnWaiver.Models.WaiverStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserFullName")
                        .HasColumnType("text");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("DeletedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedUserFullName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WaiverStatus");
                });

            modelBuilder.Entity("PtnWaiver.Models.Waiver", b =>
                {
                    b.HasOne("PtnWaiver.Models.PTN", "PTN")
                        .WithMany("Waivers")
                        .HasForeignKey("PTNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PTN");
                });

            modelBuilder.Entity("PtnWaiver.Models.PTN", b =>
                {
                    b.Navigation("Waivers");
                });
#pragma warning restore 612, 618
        }
    }
}
